#!/usr/bin/env bash
# Regenerate the "What each format looks like" block in README.md.
#
# Source of truth is the `mixed` golden for each format under
# render/testdata/<format>/mixed.golden — the same one-suite fixture
# (a passing, failing, skipped, and pending spec) the render tests
# verify on every `go test ./render/...`. Reading the goldens, rather
# than re-running ginkgoleaf live, keeps this output deterministic
# (no timestamps, durations, or seeds vary run to run) and guarantees
# the README can only show output the test suite already attests to.
#
# Output is spliced between the BEGIN/END markers in README.md. Run via
# `go tool task docs:formats`. Idempotent: re-running with unchanged
# goldens produces an identical README.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
README="$ROOT/README.md"
GOLDEN_DIR="$ROOT/render/testdata"

BEGIN='<!-- BEGIN:format-examples (generated by tools/gen-format-docs.sh — do not edit) -->'
END='<!-- END:format-examples -->'

# Table order matches the Formats table above the examples in README.md.
formats=(tree jest markdown github gitlab text shell tap)

declare -A lang=(
	[tree]=text [jest]=text [markdown]=markdown [github]=text
	[gitlab]=text [text]=text [shell]=text [tap]=text
)

declare -A desc=(
	[tree]="default human format — box-drawing tree per suite"
	[jest]="streaming, jest-style with check/✗ glyphs and BDD headers"
	[markdown]="collapsible &lt;details&gt; blocks (Markdown source shown)"
	[github]="GitHub Actions workflow commands"
	[gitlab]="GitLab CI section markers (terminal colors stripped)"
	[text]="plain ASCII, never colored"
	[shell]="tab-separated records for grep/awk"
	[tap]="TAP 14 with YAML diagnostics"
)

if ! grep -qF "$BEGIN" "$README" || ! grep -qF "$END" "$README"; then
	echo "FAIL: README.md is missing the format-example markers; add them once before running this." >&2
	exit 1
fi

# Make terminal output printable in a Markdown code fence: drop CSI escape
# sequences (color, the gitlab ESC[0K erase-line), turn the gitlab
# carriage return into a space so the section marker and its header stay
# legibly separated, and trim trailing whitespace.
strip_control() {
	sed -e 's/\r/ /g' \
		-e 's/\x1b\[[0-9;]*[A-Za-z]//g' \
		-e 's/[[:space:]]*$//' "$1"
}

GEN="$(mktemp)"
trap 'rm -f "$GEN"' EXIT

printf '\n' >"$GEN"
for f in "${formats[@]}"; do
	golden="$GOLDEN_DIR/$f/mixed.golden"
	if [[ ! -f "$golden" ]]; then
		echo "FAIL: missing golden $golden — run 'go tool task go:golden:update' first." >&2
		exit 1
	fi

	content="$(strip_control "$golden")"

	# Pick a fence longer than any backtick run in the content (the
	# markdown format embeds a ```text fence, so it needs 4 backticks).
	max_ticks="$(printf '%s\n' "$content" | { grep -oE '`+' || true; } | awk '{ if (length > m) m = length } END { print m + 0 }')"
	fence_n=3
	if ((max_ticks + 1 > fence_n)); then
		fence_n=$((max_ticks + 1))
	fi
	fence="$(printf '`%.0s' $(seq 1 "$fence_n"))"

	{
		echo "<details>"
		echo "<summary><code>$f</code> — ${desc[$f]}</summary>"
		echo
		echo "${fence}${lang[$f]}"
		printf '%s\n' "$content"
		echo "${fence}"
		echo
		echo "</details>"
		echo
	} >>"$GEN"
done

# Splice GEN between the markers, replacing whatever was there before.
TMP="$(mktemp)"
trap 'rm -f "$GEN" "$TMP"' EXIT
awk -v begin="$BEGIN" -v end="$END" -v gen="$GEN" '
	$0 == begin { print; while ((getline line < gen) > 0) print line; close(gen); skip = 1; next }
	$0 == end   { skip = 0; print; next }
	skip == 1   { next }
	{ print }
' "$README" >"$TMP"
# Overwrite in place (not mv) so the file keeps its existing ownership and
# SELinux context — mv onto a bind mount trips a harmless but noisy
# "setting attribute security.selinux" warning.
cat "$TMP" >"$README"

echo "Updated $README format examples (${#formats[@]} formats)."
